### ISSUE TITLE
Edge case when displaying the preview of Mirror content

### ISSUE THREAD

**Issue by Jasmine-liang** [NaturalSelectionLabs/Revery#51]
When there is a code section at the beginning of the article, this issue happens:
![ISSUE](https://user-images.githubusercontent.com/63624438/148380732-943d0ba4-a57e-4d09-9f83-56d48f46dcb0.png)
![BUG](https://user-images.githubusercontent.com/63624438/148507215-d3d2452c-63bd-4971-b327-fa426111e30d.jpg)

- Environment:
Linux | chrome version: 96.0.4664.45
- Related Mirror article: [Article with code section at the beginning]
(https://mirror.xyz/bingnan.eth/OOyLaF_FXL3WeIeOSTToT7hz67qrUTUFSKcmcPfPaUU)

**Comment by akasuv** [comment]
Anyone on this? I can help with it.
